# site settings

title: Kenny Tran
description: Kenny Tran's personal website
taglong: CS @ UC Santa Barbara
tagshort: CS @ UC Santa Barbara
url: https://khtran1.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/khtran1/khtran1.github.io

# author settings

author:
  name: Kenny Tran
  email: kennytran4302@gmail.com
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
